// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose;

  mongoose = require("mongoose");

  exports.timestamps = function(schema, options) {
    if (!options) {
      options = {};
    }
    schema.add({
      createdAt: Date,
      updatedAt: Date
    });
    return schema.pre("save", function(next) {
      if (!this.createdAt) {
        this.createdAt = this.updatedAt = new Date;
      } else {
        this.updatedAt = new Date;
      }
      return next();
    });
  };

}).call(this);
